# -*- coding: utf-8 -*-
"""untitiled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11noMaC0iVrtjoVH9DNDgzJHt86Oy0AFf
"""

from google.colab import drive
drive.mount('/content/drive')

import os
PROJECT_DIR = "/content/drive/MyDrive/ml_model1"
os.makedirs(f"{PROJECT_DIR}/data", exist_ok=True)
os.makedirs(f"{PROJECT_DIR}/checkpoints", exist_ok=True)

import os

if not os.path.exists(f"{PROJECT_DIR}/data/images.zip"):
    !wget -q "https://zenodo.org/records/15298010/files/images.zip?download=1" -O "{PROJECT_DIR}/data/images.zip"
if not os.path.exists(f"{PROJECT_DIR}/data/masks.zip"):
    !wget -q "https://zenodo.org/records/15298010/files/masks.zip?download=1" -O "{PROJECT_DIR}/data/masks.zip"

print(os.listdir(f"{PROJECT_DIR}/data"))

!mkdir -p /content/dataset
!unzip -q "{PROJECT_DIR}/data/images.zip" -d /content/dataset/images
!unzip -q "{PROJECT_DIR}/data/masks.zip" -d /content/dataset/masks
!find /content/dataset -maxdepth 3 -type d

import os
from PIL import Image
import numpy as np

IMG_TRAIN = "/content/dataset/images/images/train"
MASK_TRAIN = "/content/dataset/masks/masks/train"
IMG_VAL = "/content/dataset/images/images/val"
MASK_VAL = "/content/dataset/masks/masks/val"

for name, path in [("img_train", IMG_TRAIN), ("mask_train", MASK_TRAIN),
                    ("img_val", IMG_VAL), ("mask_val", MASK_VAL)]:
    files = sorted(os.listdir(path))
    print(f"{name}: {len(files)} files, e.g. {files[:3]}")

# check filename correspondence
img_files = set(os.listdir(IMG_TRAIN))
mask_files = set(os.listdir(MASK_TRAIN))
print("\nSame filenames in img/mask train?", img_files == mask_files)
print("Only in images:", list(img_files - mask_files)[:5])
print("Only in masks:", list(mask_files - img_files)[:5])

# sample image/mask inspection
sample_name = sorted(img_files)[0]
img = Image.open(os.path.join(IMG_TRAIN, sample_name))
mask = Image.open(os.path.join(MASK_TRAIN, sample_name))
img_arr = np.array(img)
mask_arr = np.array(mask)

print(f"\nSample image: {sample_name}")
print("Image mode:", img.mode, "size:", img.size)
print("Image array shape/dtype:", img_arr.shape, img_arr.dtype, "min/max:", img_arr.min(), img_arr.max())
print("\nMask mode:", mask.mode, "size:", mask.size)
print("Mask array shape/dtype:", mask_arr.shape, mask_arr.dtype)
print("Unique mask values:", np.unique(mask_arr))

import numpy as np

print("Are R, G, B channels identical?",
      np.array_equal(img_arr[:,:,0], img_arr[:,:,1]) and np.array_equal(img_arr[:,:,1], img_arr[:,:,2]))

import numpy as np

print("Are mask R, G, B channels identical?",
      np.array_equal(mask_arr[:,:,0], mask_arr[:,:,1]) and np.array_equal(mask_arr[:,:,1], mask_arr[:,:,2]))

import torch
from torch.utils.data import Dataset
from PIL import Image
import numpy as np

class OilSpillDataset(Dataset):
    def __init__(self, img_dir, mask_dir):
        self.img_dir = img_dir
        self.mask_dir = mask_dir
        self.filenames = sorted(os.listdir(img_dir))

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        fname = self.filenames[idx]

        img = Image.open(os.path.join(self.img_dir, fname)).convert("L")
        mask = Image.open(os.path.join(self.mask_dir, fname)).convert("L")

        img_arr = np.array(img, dtype=np.float32) / 255.0        # scale to [0,1]
        mask_arr = (np.array(mask, dtype=np.float32) > 127).astype(np.float32)  # binarize to {0,1}

        img_tensor = torch.from_numpy(img_arr).unsqueeze(0)      # (1, H, W)
        mask_tensor = torch.from_numpy(mask_arr).unsqueeze(0)    # (1, H, W)

        return img_tensor, mask_tensor

train_dataset = OilSpillDataset(IMG_TRAIN, MASK_TRAIN)
print("Train dataset length:", len(train_dataset))

from torch.utils.data import DataLoader

val_dataset = OilSpillDataset(IMG_VAL, MASK_VAL)
print("Train dataset length:", len(train_dataset))
print("Val dataset length:", len(val_dataset))

BATCH_SIZE = 16

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

# sanity check one batch
x_batch, y_batch = next(iter(train_loader))
print("\nBatch image shape:", x_batch.shape)
print("Batch mask shape:", y_batch.shape)
print("Batch image dtype/min/max:", x_batch.dtype, x_batch.min().item(), x_batch.max().item())
print("Batch mask dtype/unique:", y_batch.dtype, torch.unique(y_batch))

import torch.nn as nn
###############################################################################################
###############################################################################################
###############################################################################################
###############################################################################################

class ConvBlock(nn.Module):
    """Two 3x3 conv layers, each followed by BatchNorm + ReLU."""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.block(x)

# quick sanity test
test_block = ConvBlock(1, 32)
test_input = torch.randn(2, 1, 256, 256)  # batch of 2, 1 channel, 256x256
test_output = test_block(test_input)
print("Input shape:", test_input.shape)
print("Output shape:", test_output.shape)
###############################################################################################
###############################################################################################
###############################################################################################
###############################################################################################

class DownBlock(nn.Module):
    """ConvBlock followed by 2x2 max pooling. Returns both the pre-pool feature map
    (needed later for skip connections) and the pooled output (goes deeper into encoder)."""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = ConvBlock(in_channels, out_channels)
        self.pool = nn.MaxPool2d(kernel_size=2)

    def forward(self, x):
        skip = self.conv(x)      # full-resolution features, saved for skip connection
        down = self.pool(skip)   # downsampled, passed to next encoder stage
        return skip, down

# quick sanity test
test_down = DownBlock(1, 32)
test_input = torch.randn(2, 1, 256, 256)
skip_out, down_out = test_down(test_input)
print("Input shape:", test_input.shape)
print("Skip shape (pre-pool):", skip_out.shape)
print("Down shape (post-pool):", down_out.shape)
###############################################################################################
###############################################################################################
###############################################################################################
###############################################################################################
class AttentionGate(nn.Module):
    """
    Takes:
      - g: gating signal from the decoder (coarser, deeper features)
      - x: skip connection from the encoder (finer, shallower features)
    Outputs: x reweighted by a learned attention map (same shape as x)
    """
    def __init__(self, g_channels, x_channels, inter_channels):
        super().__init__()
        self.W_g = nn.Sequential(
            nn.Conv2d(g_channels, inter_channels, kernel_size=1),
            nn.BatchNorm2d(inter_channels)
        )
        self.W_x = nn.Sequential(
            nn.Conv2d(x_channels, inter_channels, kernel_size=1, stride=2),  # stride=2 to match g's spatial size
            nn.BatchNorm2d(inter_channels)
        )
        self.psi = nn.Sequential(
            nn.Conv2d(inter_channels, 1, kernel_size=1),
            nn.BatchNorm2d(1),
            nn.Sigmoid()
        )
        self.relu = nn.ReLU(inplace=True)
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)

    def forward(self, g, x):
        g1 = self.W_g(g)
        x1 = self.W_x(x)
        psi = self.relu(g1 + x1)
        psi = self.psi(psi)
        psi = self.upsample(psi)   # back to x's spatial resolution
        return x * psi

# quick sanity test
test_gate = AttentionGate(g_channels=64, x_channels=32, inter_channels=16)
g_test = torch.randn(2, 64, 32, 32)
x_test = torch.randn(2, 32, 64, 64)
out = test_gate(g_test, x_test)
print("g shape:", g_test.shape)
print("x shape:", x_test.shape)
print("Attention-gated output shape:", out.shape)
###############################################################################################
###############################################################################################
###############################################################################################
###############################################################################################
class UpBlock(nn.Module):
    """
    Upsamples decoder features, applies attention gate to the skip connection,
    concatenates both, then refines with a ConvBlock.
    """
    def __init__(self, in_channels, skip_channels, out_channels):
        super().__init__()
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.attn = AttentionGate(g_channels=in_channels, x_channels=skip_channels, inter_channels=skip_channels // 2)
        self.conv = ConvBlock(in_channels + skip_channels, out_channels)

    def forward(self, x, skip):
        # x: deeper decoder features (before upsampling)
        # skip: corresponding encoder skip connection (finer resolution)
        attn_skip = self.attn(g=x, x=skip)   # reweight skip using attention (uses x at its original resolution)
        x = self.upsample(x)                 # upsample decoder features to match skip's resolution
        x = torch.cat([x, attn_skip], dim=1) # concatenate along channel dim
        x = self.conv(x)
        return x

# quick sanity test
test_up = UpBlock(in_channels=64, skip_channels=32, out_channels=32)
x_test = torch.randn(2, 64, 32, 32)
skip_test = torch.randn(2, 32, 64, 64)
out = test_up(x_test, skip_test)
print("x shape:", x_test.shape)
print("skip shape:", skip_test.shape)
print("Output shape:", out.shape)
###############################################################################################
###############################################################################################
###############################################################################################
###############################################################################################
class AttentionUNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1, base_channels=32):
        super().__init__()
        c = base_channels

        # Encoder
        self.down1 = DownBlock(in_channels, c)       # 256 -> 128, c
        self.down2 = DownBlock(c, c * 2)              # 128 -> 64, 2c
        self.down3 = DownBlock(c * 2, c * 4)          # 64 -> 32, 4c
        self.down4 = DownBlock(c * 4, c * 8)          # 32 -> 16, 8c

        # Bottleneck
        self.bottleneck = ConvBlock(c * 8, c * 16)     # 16x16, 16c

        # Decoder (with attention gates inside UpBlock)
        self.up4 = UpBlock(in_channels=c * 16, skip_channels=c * 8, out_channels=c * 8)   # -> 32x32
        self.up3 = UpBlock(in_channels=c * 8,  skip_channels=c * 4, out_channels=c * 4)   # -> 64x64
        self.up2 = UpBlock(in_channels=c * 4,  skip_channels=c * 2, out_channels=c * 2)   # -> 128x128
        self.up1 = UpBlock(in_channels=c * 2,  skip_channels=c,     out_channels=c)       # -> 256x256

        # Output head
        self.out_conv = nn.Conv2d(c, out_channels, kernel_size=1)

    def forward(self, x):
        skip1, x = self.down1(x)   # skip1: c, 256x256   | x: c, 128x128
        skip2, x = self.down2(x)   # skip2: 2c, 128x128  | x: 2c, 64x64
        skip3, x = self.down3(x)   # skip3: 4c, 64x64    | x: 4c, 32x32
        skip4, x = self.down4(x)   # skip4: 8c, 32x32    | x: 8c, 16x16

        x = self.bottleneck(x)     # 16c, 16x16

        x = self.up4(x, skip4)     # 8c, 32x32
        x = self.up3(x, skip3)     # 4c, 64x64
        x = self.up2(x, skip2)     # 2c, 128x128
        x = self.up1(x, skip1)     # c, 256x256

        return self.out_conv(x)    # out_channels, 256x256

# quick sanity test
test_model = AttentionUNet(in_channels=1, out_channels=1, base_channels=32)
test_input = torch.randn(2, 1, 256, 256)
test_output = test_model(test_input)

print("Input shape:", test_input.shape)
print("Output shape:", test_output.shape)

total_params = sum(p.numel() for p in test_model.parameters())
print(f"Total parameters: {total_params:,}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

model = AttentionUNet(in_channels=1, out_channels=1, base_channels=32).to(device)

class DiceBCELoss(nn.Module):
    def __init__(self, smooth=1.0):
        super().__init__()
        self.smooth = smooth
        self.bce = nn.BCEWithLogitsLoss()

    def forward(self, logits, targets):
        bce_loss = self.bce(logits, targets)

        probs = torch.sigmoid(logits)
        probs_flat = probs.view(-1)
        targets_flat = targets.view(-1)
        intersection = (probs_flat * targets_flat).sum()
        dice_loss = 1 - (2. * intersection + self.smooth) / (probs_flat.sum() + targets_flat.sum() + self.smooth)

        return bce_loss + dice_loss

criterion = DiceBCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# sanity test: one forward pass + loss computation on a real batch, no backward yet
x_batch, y_batch = next(iter(train_loader))
x_batch, y_batch = x_batch.to(device), y_batch.to(device)

logits = model(x_batch)
loss = criterion(logits, y_batch)

print("Logits shape:", logits.shape)
print("Loss value:", loss.item())

import time

model.train()
num_test_batches = 10  # just a handful of batches to sanity-check training works

start = time.time()
for i, (x_batch, y_batch) in enumerate(train_loader):
    if i >= num_test_batches:
        break

    x_batch, y_batch = x_batch.to(device), y_batch.to(device)

    optimizer.zero_grad()
    logits = model(x_batch)
    loss = criterion(logits, y_batch)
    loss.backward()
    optimizer.step()

    print(f"Batch {i+1}/{num_test_batches} - Loss: {loss.item():.4f}")

print(f"\nTime for {num_test_batches} batches: {time.time() - start:.1f}s")

import os

NUM_EPOCHS = 5
best_val_loss = float('inf')
checkpoint_path = f"{PROJECT_DIR}/checkpoints/attention_unet_best.pth"

history = {"train_loss": [], "val_loss": []}

for epoch in range(NUM_EPOCHS):
    # --- Training ---
    model.train()
    train_loss_total = 0.0
    for x_batch, y_batch in train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)

        optimizer.zero_grad()
        logits = model(x_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()

        train_loss_total += loss.item() * x_batch.size(0)

    train_loss = train_loss_total / len(train_dataset)

    # --- Validation ---
    model.eval()
    val_loss_total = 0.0
    with torch.no_grad():
        for x_batch, y_batch in val_loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            logits = model(x_batch)
            loss = criterion(logits, y_batch)
            val_loss_total += loss.item() * x_batch.size(0)

    val_loss = val_loss_total / len(val_dataset)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)

    print(f"Epoch {epoch+1}/{NUM_EPOCHS} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    # save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), checkpoint_path)
        print(f"  -> Saved new best model (val_loss: {val_loss:.4f})")

print("\nTraining complete.")
print("History:", history)

import torch
import numpy as np

def compute_metrics(model, loader, device, threshold=0.5, eps=1e-7):
    model.eval()
    tp = fp = fn = tn = 0

    with torch.no_grad():
        for x_batch, y_batch in loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            logits = model(x_batch)
            probs = torch.sigmoid(logits)
            preds = (probs > threshold).float()

            tp += ((preds == 1) & (y_batch == 1)).sum().item()
            fp += ((preds == 1) & (y_batch == 0)).sum().item()
            fn += ((preds == 0) & (y_batch == 1)).sum().item()
            tn += ((preds == 0) & (y_batch == 0)).sum().item()

    precision = tp / (tp + fp + eps)
    recall = tp / (tp + fn + eps)
    f1 = 2 * precision * recall / (precision + recall + eps)
    dice = 2 * tp / (2 * tp + fp + fn + eps)
    iou = tp / (tp + fp + fn + eps)
    iou_bg = tn / (tn + fp + fn + eps)
    miou = (iou + iou_bg) / 2

    return {
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Dice": dice,
        "IoU (oil class)": iou,
        "mIoU": miou,
    }

# load best checkpoint before evaluating
model.load_state_dict(torch.load(checkpoint_path, map_location=device))

val_metrics = compute_metrics(model, val_loader, device)
print("Validation metrics (best checkpoint):")
for k, v in val_metrics.items():
    print(f"  {k}: {v:.4f}")

import matplotlib.pyplot as plt

def visualize_predictions(model, dataset, device, num_samples=4, threshold=0.5):
    model.eval()
    fig, axes = plt.subplots(num_samples, 3, figsize=(9, 3 * num_samples))

    indices = np.random.choice(len(dataset), num_samples, replace=False)

    with torch.no_grad():
        for row, idx in enumerate(indices):
            img_tensor, mask_tensor = dataset[idx]
            x = img_tensor.unsqueeze(0).to(device)
            logits = model(x)
            pred = (torch.sigmoid(logits) > threshold).float().cpu().squeeze().numpy()

            img_np = img_tensor.squeeze().numpy()
            mask_np = mask_tensor.squeeze().numpy()

            axes[row, 0].imshow(img_np, cmap='gray')
            axes[row, 0].set_title("Input")
            axes[row, 1].imshow(mask_np, cmap='gray')
            axes[row, 1].set_title("Ground Truth")
            axes[row, 2].imshow(pred, cmap='gray')
            axes[row, 2].set_title("Prediction")

            for ax in axes[row]:
                ax.axis('off')

    plt.tight_layout()
    plt.savefig(f"{PROJECT_DIR}/checkpoints/sample_predictions.png", dpi=150)
    plt.show()

visualize_predictions(model, val_dataset, device, num_samples=4)

import matplotlib.pyplot as plt

plt.figure(figsize=(7, 5))
plt.plot(range(1, len(history["train_loss"]) + 1), history["train_loss"], label="Train Loss", marker='o')
plt.plot(range(1, len(history["val_loss"]) + 1), history["val_loss"], label="Val Loss", marker='o')
plt.xlabel("Epoch")
plt.ylabel("Loss (BCE + Dice)")
plt.title("Attention U-Net Training Curve — Model 1")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{PROJECT_DIR}/checkpoints/loss_curve.png", dpi=150)
plt.show()

import json

results = {
    "model": "Attention U-Net (Model 1 — Oil Spill Segmentation)",
    "dataset": {
        "train_images": len(train_dataset),
        "val_images": len(val_dataset),
        "image_size": "256x256",
        "input_channels": 1,
    },
    "training": {
        "epochs": NUM_EPOCHS,
        "batch_size": BATCH_SIZE,
        "optimizer": "Adam",
        "lr": 1e-4,
        "loss": "BCE + Dice",
        "train_loss_history": history["train_loss"],
        "val_loss_history": history["val_loss"],
        "best_val_loss": best_val_loss,
    },
    "validation_metrics": val_metrics,
    "total_params": total_params,
    "checkpoint_path": checkpoint_path,
}

results_path = f"{PROJECT_DIR}/checkpoints/results.json"
with open(results_path, "w") as f:
    json.dump(results, f, indent=2)

print("Saved:", results_path)
print(json.dumps(results, indent=2))

NUM_EPOCHS_EXTRA = 10  # additional epochs on top of the 5 already done

for epoch in range(NUM_EPOCHS_EXTRA):
    # --- Training ---
    model.train()
    train_loss_total = 0.0
    for x_batch, y_batch in train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)

        optimizer.zero_grad()
        logits = model(x_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()

        train_loss_total += loss.item() * x_batch.size(0)

    train_loss = train_loss_total / len(train_dataset)

    # --- Validation ---
    model.eval()
    val_loss_total = 0.0
    with torch.no_grad():
        for x_batch, y_batch in val_loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            logits = model(x_batch)
            loss = criterion(logits, y_batch)
            val_loss_total += loss.item() * x_batch.size(0)

    val_loss = val_loss_total / len(val_dataset)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)

    epoch_num = len(history["train_loss"])
    print(f"Epoch {epoch_num} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), checkpoint_path)
        print(f"  -> Saved new best model (val_loss: {val_loss:.4f})")

print("\nExtended training complete.")

# re-evaluate now that training has continued past epoch 5
model.load_state_dict(torch.load(checkpoint_path, map_location=device))

val_metrics = compute_metrics(model, val_loader, device)
print(f"Validation metrics after {len(history['train_loss'])} epochs (best checkpoint):")
for k, v in val_metrics.items():
    print(f"  {k}: {v:.4f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(7, 5))
plt.plot(range(1, len(history["train_loss"]) + 1), history["train_loss"], label="Train Loss", marker='o')
plt.plot(range(1, len(history["val_loss"]) + 1), history["val_loss"], label="Val Loss", marker='o')
plt.xlabel("Epoch")
plt.ylabel("Loss (BCE + Dice)")
plt.title("Attention U-Net Training Curve — Model 1 (Full Run)")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{PROJECT_DIR}/checkpoints/loss_curve.png", dpi=150)
plt.show()

visualize_predictions(model, val_dataset, device, num_samples=4)

import numpy as np

def sweep_thresholds(model, loader, device, thresholds=None, eps=1e-7):
    if thresholds is None:
        thresholds = np.arange(0.3, 0.75, 0.05)

    model.eval()
    results = []

    # collect all probs/targets once, then just re-threshold (faster than re-running the model per threshold)
    all_probs, all_targets = [], []
    with torch.no_grad():
        for x_batch, y_batch in loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            logits = model(x_batch)
            all_probs.append(torch.sigmoid(logits).cpu())
            all_targets.append(y_batch.cpu())
    all_probs = torch.cat(all_probs)
    all_targets = torch.cat(all_targets)

    for t in thresholds:
        preds = (all_probs > t).float()
        tp = ((preds == 1) & (all_targets == 1)).sum().item()
        fp = ((preds == 1) & (all_targets == 0)).sum().item()
        fn = ((preds == 0) & (all_targets == 1)).sum().item()

        precision = tp / (tp + fp + eps)
        recall = tp / (tp + fn + eps)
        f1 = 2 * precision * recall / (precision + recall + eps)
        dice = 2 * tp / (2 * tp + fp + fn + eps)

        results.append({"threshold": round(float(t), 2), "precision": precision,
                         "recall": recall, "f1": f1, "dice": dice})

    return results

model.load_state_dict(torch.load(checkpoint_path, map_location=device))
threshold_results = sweep_thresholds(model, val_loader, device)

print(f"{'Thresh':>7} {'Precision':>10} {'Recall':>8} {'F1':>8} {'Dice':>8}")
for r in threshold_results:
    print(f"{r['threshold']:>7} {r['precision']:>10.4f} {r['recall']:>8.4f} {r['f1']:>8.4f} {r['dice']:>8.4f}")

best = max(threshold_results, key=lambda r: r["dice"])
print(f"\nBest threshold by Dice: {best['threshold']} (Dice={best['dice']:.4f}, F1={best['f1']:.4f})")

import json
from datetime import datetime

results = {
    "model": "Attention U-Net (Model 1 — Oil Spill Segmentation)",
    "dataset": {
        "source": "Refined Deep-SAR Oil Spill (SOS) — Zenodo",
        "train_images": len(train_dataset),
        "val_images": len(val_dataset),
        "test_split": "No separate test set was available in this dataset (only train/val); "
                       "validation set doubled as the held-out test set for this MVP. "
                       "No additional hyperparameter tuning was done beyond the decision threshold sweep below.",
        "image_size": "256x256",
        "input_channels": 1,
    },
    "training": {
        "epochs": len(history["train_loss"]),
        "batch_size": BATCH_SIZE,
        "optimizer": "Adam",
        "lr": 1e-4,
        "loss": "BCE + Dice",
        "train_loss_history": history["train_loss"],
        "val_loss_history": history["val_loss"],
        "best_val_loss": best_val_loss,
    },
    "validation_metrics_at_0.5": val_metrics,
    "threshold_sweep": threshold_results,
    "best_threshold": best,
    "final_test_metrics": val_metrics,  # val doubled as test — see dataset.test_split note above
    "total_params": total_params,
    "checkpoint_path": checkpoint_path,
    "completed_at": datetime.now().isoformat(),
}

results_path = f"{PROJECT_DIR}/checkpoints/results.json"
with open(results_path, "w") as f:
    json.dump(results, f, indent=2)

print("Saved:", results_path)
print(json.dumps(results, indent=2))